name: balanced_text
description: A Flutter widget that simply balances the lines of two-line text
version: 0.0.1
homepage: https://github.com/rasitayaz/flutter-balanced-text
repository: https://github.com/rasitayaz/flutter-balanced-text
issue_tracker: https://github.com/rasitayaz/flutter-balanced-text/issues

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
